package ca.ubc.cs.beta.aclib.random;

public enum SeedableRandomPoolConstants {
	RANDOM_CONFIG_POOL,
	INCUMBENT_INSTANCE_SELECTOR, 
	INSTANCE_SEEDS,
	TEST_SEED_INSTANCES,
	VALIDATE_RANDOM_CONFIG_POOL,
	INITIAL_INCUMBENT_SELECTION;
	
}
